# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux

julia:
  - 1.3

matrix:
  allow_failures:
    - julia: nightly

branches:
  only: 
    - master    
    
notifications: 
  email: false
